
services:
  postgres:
    image: postgres:16
    container_name: inventario_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: INVENTARIOESCOLAR
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventario_net

  api:
    build:
      context: .
      dockerfile: src/Backend/InventarioEscolar.Api/Dockerfile
    container_name: inventario_api
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=INVENTARIOESCOLAR;Username=postgres;Password=123456"
    ports:
      - "8080:8080"
    networks:
      - inventario_net

  frontend:
    build:
      context: ./frontend/EscolarInventarioApp
      dockerfile: Dockerfile
    container_name: inventario_front
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - inventario_net

networks:
  inventario_net:

volumes:
  postgres_data:
