services:
  inventarioescolar.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__ConnectionSQLServer=Server=sqlserver,1433;Database=INVENTARIOESCOLAR;User Id=sa;Password=Teste123@;TrustServerCertificate=True;
    ports:
      - "8080:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - inventario-network
