services:
  postgres:
    image: postgres:16
    container_name: inventario_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventario_net

  api:
    build:
      context: .
      dockerfile: src/Backend/InventarioEscolar.Api/Dockerfile
    container_name: inventario_api
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__DefaultConnection: ${CONNECTION_STRING}
    ports:
      - "8080:8080"
    networks:
      - inventario_net

  frontend:
    build:
      context: ./frontend/EscolarInventarioApp
      dockerfile: Dockerfile
    container_name: inventario_front
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - inventario_net

networks:
  inventario_net:


volumes:
  postgres_data:
